name: Check if version in setup.cfg has been changed
on: [push]
jobs:
  simple-version-change-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo with deeper fetch depth than usual
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - name: Check if version has changed
        run: git diff HEAD HEAD^ setup.cfg | grep -q '+version =' || exit 1